import { AuthorService } from './author/author.service';
import { CoursesService } from './courses/courses.service';
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { CoursesComponent } from './courses/courses.component';
import { CourseComponent } from './course/course.component';
import { AuthorComponent } from './author/author.component';

// another declarator function, converts plain TS to a module from angular's POV, do not worry about the properties in the declarator atm
// to add a component that is part of this module, include it in the declarations property block
@NgModule({
  declarations: [
    AppComponent,  // generated by default
    CoursesComponent, CourseComponent, AuthorComponent  // remember to add the import or use plugin extension auto import
  ],
  imports: [
    BrowserModule,
    AppRoutingModule
  ],
  providers: [CoursesService, AuthorService],  // register all the dependencies, components in THIS module are dependent on
  bootstrap: [AppComponent]
})
export class AppModule { }
